# Key bindings:
# The format for specifying key sequence is vim-style-like.
# Following keys are supported: 
#
# <C-key>						: Ctrl-key 			# (Ctrl pressed with a key, key can be any of a..z or one of special keys
# listed below)	 
# <S-key>						: Shift-key 
# <A-key>/<M-key>		: Alt-key
#	
# <BS>							: Backspace
# <Tab>							: Tab
# <CR>							: Enter
# <Enter>						: Enter
# <Return>					: Enter
# <Esc>							: Escape
#	<Space>						: Space
#	<Up>							: Up arrow
#	<Down>						: Down arrow
#	<Left>						: Left arrow
#	<Right>						: Right arrow
# <F1> - <F12>			: Function keys 1 to 12
# <Insert>					: Insert
# <Del>							: Delete	
# <Home>						: Home
# <End>							: End
# <PageUp>					: Page-Up
# <PageDown>				: Page-Down
# a..z							: a to z keys					# Note all alphabetic keys must be lower-case
#
# Some valid examples of key-combinations are : <C-Tab>, <C-a>g, gg, <Space>x, g<Esc>

##############################################################################################################
[key-bindings]

# Application
app_quit														= "zz"					# Quit

##############################################################################################################
[tui]

# Interface
interface.mouse-events-enable				= true 

# Theme
theme.highlight-fg									= "#030F04"
theme.highlight-bg									= "#0df93f"

theme.post-header-fg								= "#030F04"
theme.post-header-bg								= "#0df93f"
theme.post-upvoted-fg								= "#fafafa"
theme.post-upvoted-bg								= "#060303"
theme.post-heading-fg								= "#030F04"
theme.post-heading-bg								= "#0df93f"
theme.post-body-fg									= "#f000ff"
theme.post-body-bg									= "#000000"
