name: generate_changelog
on:
  pull_request:
    types: [ opened ]

jobs:
  project:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run Changelog CI
        uses: saadmk11/changelog-ci@v1.0.0
        with:
          changelog_filename: CHANGELOG.md
          github_token: ${{ secrets.GITHUB_TOKEN }}
