name: project
on:
  - pull_request_target
jobs:
  label_pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@v3
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
  todo_to_issue: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: TODO to Issue
        uses: alstr/todo-to-issue-action@v4.5
        id: todo
